### ISSUE TITLE
Ask a question about checking nonce in func ethAnteHandler

### ISSUE THREAD

**Issue by james-ray** [cosmos/ethermint#157] opened 2019-11-21 03:48 UTC
```
// no need to increment sequence on CheckTx or RecheckTx
	if !(ctx.IsCheckTx() && !sim) {
		// increment sequence of sender
		acc := ak.GetAccount(ctx, senderAddr)
		if err := acc.SetSequence(acc.GetSequence() + 1); err != nil {
			panic(err)
		}
		ak.SetAccount(ctx, acc)
	}
```

I am using a very old version of ethermint, which starts a goroutine to receive TxPreEvent of Ethereum and call CheckTx of Tendermint.
I am new to the branch here, and I am confused to find the logic of not increasing nonce on CheckTx.
If the nonce does not increase in the CheckTx phase, how can we defend the replay attack? which means the same transaction package be sent to the node again and again.

**Comment by austinabell** [comment] 2019-11-21 14:12
Yes, this may be confusing logic to follow and I can maybe clear up the syntax of it and explain better in the code. This increment skip is the same logic as is done with standard Cosmos txs [here](https://github.com/cosmos/cosmos-sdk/blob/a13909a9ffaafda31c26a104a4fc97efa947f597/x/auth/ante/sigverify.go#L240). This still protects against replay attacks because the Ante handler is passed through twice, once to put the tx in the mempool and once before the tx state transition happens. This just doesn't increase the nonce when put in the mempool (because state is reset after this check anyway so increasing the nonce does not do anything). 

You can test this by sending two transactions with the same nonce before a block is finalized, they will both pass the mempool check (unfortunately with the way Cosmos/Tendermint is setup this can't be rejected here) but only the first transaction will be processed in the state transition and the other will be rejected.

Let me know if this helps, I'll keep the issue open for a bit in case you want to follow up on any of this :)

**Comment by james-ray** [comment] 2019-11-21 16:12
What you said confirms what I am guessing.   But can’t we do this better? The api sendTransaction will return the same nonce within one block, it’s terrible when doing performance test.   Why not we increase it and make the api return an increased nonce?
And for the sendrawtransaction,  even the client sends two transactions with increased nonces, the second one will fail in checktx, this doesn’t make sense, does it?

**Comment by austinabell** [comment] 2019-11-21 16:16
> What you said confirms what I am guessing. But can’t we do this better? The api sendTransaction will return the nonce within one block, it’s terrible when doing performance test. Why not we increase it and make the api return an increased nonce!

That would be great and it was considered previously to cache this increase for the server, but there would be inconsistencies of the nonce with transactions that did not go through the RPC API. If you need this for a specific case and you can guarantee you only interface through the RPC API, you can just fork and cache these pending tx nonce increases.

It is kept as a goal, but is not possible given the current system outside of the context of Ethermint

**Comment by james-ray** [comment] 2019-11-21 16:21
What other cases does it be modified? After each block we reset the nonce to the current state and rechecktx make it to the correct pending nonce, so I think both need to increase the nonce

**Comment by austinabell** [comment] 2019-11-21 16:27
> What other cases does it be modified? After each block we reset the nonce to the current state and rechecktx make it to the correct pending nonce, so I think both need to increase the nonce

This is the same train of thought I had, but that increase was not being persisted in the check when the tx is placed in the mempool (I will retest now to make sure)

Edit: Yeah since the nonce isn't persisted, it can't be queried to be able to get the current "pending" nonce and I assume by design. I will keep this open for a bit to revisit and understand why this is the case because if the nonce is increased in the mempool check it will reject a tx from entering the mempool if it doesn't have the updated nonce, which seems better. (I was just trying to match the interactions with the standard Cosmos AnteHandler to not have any discrepancies with other interactions.

**Comment by james-ray** [comment] 2019-11-21 16:28
Do you mean the received tx from peer can increase the nonce too? It also needs to call checktx so I think it is no problem

**Comment by james-ray** [comment] 2019-11-21 16:37
Yes, persistence is a problem, when the node starts, all txs in the mempool need to go recheck again, or it just dropped them? I’m currently using my phone and not convenient to see the code of tendermint, I will check that later

**Comment by austinabell** [comment] 2019-11-21 16:42
> Yes, persistence is a problem, when the node starts, all txs in the mempool need to go recheck again, or it just dropped them? I’m currently using my phone and not convenient to see the code of tendermint, I will check that later

If I don't get to this before you do, let me know. 

Yeah each tx goes through the ante handler sequentially before each state transition which ensures no replay issues, and the tx will be marked as invalid in the block. It's possible this is avoided to increase in the mempool ante handler check for inconsistent transaction ordering for different nodes in a network or some other reason, but this is out of the scope of Ethermint

Edit: By the way I agree this seems like a benefit (because invalid nonces will be rejected in the mempool check instead of being included in a block as an invalidtx) but it does not solve the issue of the RPC API being able to access this "pending" nonce to send multiple txs per block without specifying a nonce explicitly (Issue ref: #129). Issue is that I don't want to have a discrepancy with the standard ante handler for compatibility reasons so will not make changes to Ethermint unless it is changed in Cosmos

**Comment by james-ray** [comment] 2019-11-22 07:59
I am sorry but I do not truly understand what hinders the optimization here, #129 seems to mention that there is a concurrent problem for the state_transition can increment the nonce at the same time, but are there two states? check_state and work_state? state_transition increments the nonce in work_state.

About the persistence problem, if I'm not mistaken Tendermint does not persist the txs in mempool. So when a node starts, the check_state simply copy from work_state, the nonce reset to current nonce.

The nonce may decrease during constant querying, e.g. if recheck delete some txs in the mempool, since we do not implement a txPool here, we can simply delete all txs after that failed check tx, e.g: there are 3,4,5,6,7,8,9 in the mempool, and there is a block come from peer which includes 3,4, so after mempool deletes the duplicate txs, there are 5,6,7,8,9 left, suppose for some reason, 7 failed the recheck, we have to delete 7,8,9, no matter 8,9 pass recheck or not. And the pending nonce of the account reset to 7.

**Comment by austinabell** [comment] 2019-11-22 19:49
> I am sorry but I do not truly understand what hinders the optimization here, #129 seems to mention that there is a concurrent problem for the state_transition can increment the nonce at the same time, but are there two states? check_state and work_state? state_transition increments the nonce in work_state.

The issue is the "check-state" is not available at the point of the RPC API (last time I checked, but will verify)

> About the persistence problem, if I'm not mistaken Tendermint does not persist the txs in mempool. So when a node starts, the check_state simply copy from work_state, the nonce reset to current nonce.

Yeah, so this would be fine to change, but I'm not going to introduce an inconsistency with Cosmos stdtxs yet, will look into it after a few things. Issue is I can't retrieve this value to be able to let the RPC API assign the correct "pending" nonce.

Edit: The logic pattern we are talking about is just for txs sent through the RPC API, if a tx is sent through the CLI it will use the other ante handler as it is a different tx struct.

> The nonce may decrease during constant querying, e.g. if recheck delete some txs in the mempool, since we do not implement a txPool here, we can simply delete all txs after that failed check tx, e.g: there are 3,4,5,6,7,8,9 in the mempool, and there is a block come from peer which includes 3,4, so after mempool deletes the duplicate txs, there are 5,6,7,8,9 left, suppose for some reason, 7 failed the recheck, we have to delete 7,8,9, no matter 8,9 pass recheck or not. And the pending nonce of the account reset to 7.

You can't just delete a pending tx during the state transition based on a criteria, it would just be marked as an invalid tx, but I get your point.

**Comment by austinabell** [comment] 2019-12-28 01:35
#164 will track this issue

**Closed as completed by austinabell** 2019-12-28 01:35 UTC
